# Generated by Django 4.1.7 on 2023-02-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
